data_folder = r'C:\TRUONG\PhD-code\OptimalConnectionPaper2023\Code\train1_val_test'
 
file_list = [
    "balance",
    "banana",
    "Breast-Tissue",
    "cleveland",
    "Colon",
    "conn-bench-vowel",
    "contraceptive",
    "electricity-normalized",
    "Embryonal",
    "fertility",
    "GM4",
    "heart",
    "isolet",
    "Leukemia",
    "madelon",
    "mammographic",
    "multiple-features",
    "musk1",
    "musk2",
    "newthyroid",
    "penbased_new_fix",
    "phoneme",
    "plant_margin",
    "ring1",
    "satimage",
    "sonar",
    "tic-tac-toe",
    "titanic_new",
    "vertebral_3C",
    "wine_red", 
]